#!/bin/bash
# Quick start script for baseline test

echo "🎯 BASELINE TEST - Sequential Processing"
echo "========================================="
echo ""
echo "Step 1: Make sure backend is running..."
echo "   $ python api_server.py"
echo ""
echo "Step 2: Go to http://localhost:3000"
echo ""
echo "Step 3: Submit test domains:"
echo "   firesand.co.uk s8080.com emagine.org bespokesupportsolutions.co.uk bcs365.co.uk"
echo ""
echo "Step 4: Copy the job_id from the response or URL"
echo ""
echo "Step 5: Run metrics capture:"
echo "   $ python capture_metrics.py <job_id>"
echo ""
echo "This will:"
echo "  - Poll job status every 1 second"
echo "  - Wait for completion (max 20 minutes)"
echo "  - Generate formatted markdown report"
echo "  - Save to baseline_results_TIMESTAMP.md"
echo ""
